### ISSUE TITLE
everytime i open the gui it crashes my game

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#100]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (cosmos-1.1.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 11/16/21 4:27 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at cope.cosmos.client.clickgui.util.BlurUtil.configureShader(BlurUtil.java:36)
	at cope.cosmos.client.clickgui.util.BlurUtil.blurRect(BlurUtil.java:73)
	at cope.cosmos.client.clickgui.windowed.window.Window.drawWindow(Window.java:67)
	at cope.cosmos.client.clickgui.windowed.window.ScrollableWindow.drawWindow(ScrollableWindow.java:35)
	at cope.cosmos.client.clickgui.windowed.window.TabbedWindow.drawWindow(TabbedWindow.java:34)
	at cope.cosmos.client.clickgui.windowed.window.windows.ConfigurationWindow.drawWindow(ConfigurationWindow.java:72)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.lambda$drawScreen$0(WindowGUI.java:36)
	at cope.cosmos.client.clickgui.windowed.WindowGUI$$Lambda$284/9337347.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.func_73863_a(WindowGUI.java:35)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cope.cosmos.client.clickgui.util.BlurUtil.configureShader(BlurUtil.java:36)
	at cope.cosmos.client.clickgui.util.BlurUtil.blurRect(BlurUtil.java:73)
	at cope.cosmos.client.clickgui.windowed.window.Window.drawWindow(Window.java:67)
	at cope.cosmos.client.clickgui.windowed.window.ScrollableWindow.drawWindow(ScrollableWindow.java:35)
	at cope.cosmos.client.clickgui.windowed.window.TabbedWindow.drawWindow(TabbedWindow.java:34)
	at cope.cosmos.client.clickgui.windowed.window.windows.ConfigurationWindow.drawWindow(ConfigurationWindow.java:72)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.lambda$drawScreen$0(WindowGUI.java:36)
	at cope.cosmos.client.clickgui.windowed.WindowGUI$$Lambda$284/9337347.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.func_73863_a(WindowGUI.java:35)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)

-- Screen render details --
Details:
	Screen name: cope.cosmos.client.clickgui.windowed.WindowGUI
	Mouse location: Scaled: (480, 254). Absolute: (960, 508)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PreparedSystem32'/16, l='MpServer', x=-691.24, y=1.00, z=591.70]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-684,4,595), Chunk: (at 4,0,3 in -43,37; contains blocks -688,0,592 to -673,255,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 41173 game time, 41173 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['PreparedSystem32'/16, l='MpServer', x=-691.24, y=1.00, z=591.70]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by linustouchtips** [comment]
Fixed in 2b47d0a
