### ISSUE TITLE
major fps drop

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#111]
this never happened with sum of the older builds but when i used the newest build i started getting 2 fps(my av fps is 370)

**Comment by master7720** [comment]
could just be a me problem but this never happened to any other client

**Comment by Sxmurai** [comment]
Send your latest.log please

**Comment by master7720** [comment]
You can't comment at this time — your comment is too long (maximum is 65536 characters).

**Comment by master7720** [comment]
:/ cant even put the log in

**Comment by linustouchtips** [comment]
just put in the last few lines, like the last 100 lines or smt

**Comment by linustouchtips** [comment]
and also dude, can you please follow the format for the love of god

**Comment by master7720** [comment]
no

**Comment by master7720** [comment]
[10:00:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:00:53] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:00:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[10:00:53] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[10:00:53] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy
[10:00:54] [main/INFO] [FML]: Searching C:\Users\tracy\AppData\Roaming\.minecraft\mods for mods
[10:00:54] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from cosmos-1.1.0.jar
[10:00:54] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:00:54] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[10:00:54] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/tracy/AppData/Roaming/.minecraft/mods/cosmos-1.1.0.jar Service=LaunchWrapper Env=CLIENT
[10:00:54] [main/WARN] [FML]: The coremod MixinLoader (cope.cosmos.asm.MixinLoader) is not signed!
[10:00:54] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[10:00:54] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[10:00:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:00:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:00:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:00:57] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[10:00:57] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[10:00:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:00:57] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[10:00:57] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@d8948cd
[10:00:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[10:00:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[10:00:58] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[10:00:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[10:00:58] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[10:00:59] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[10:01:00] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: PreparedSystem32
[10:01:06] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[10:01:06] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[10:01:07] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 890503976 bytes (849 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MixinLoader (cosmos-1.1.0.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5058' Renderer: 'Intel(R) HD Graphics 5500'
[10:01:07] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2855 Initialized
[10:01:07] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[10:01:07] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[10:01:07] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[10:01:08] [Client thread/INFO] [FML]: Searching C:\Users\tracy\AppData\Roaming\.minecraft\mods for mods
[10:01:10] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[10:01:10] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 751136100 nanos
[10:01:10] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at CLIENT
[10:01:10] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:01:11] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Cosmos, kingoros_pack.zip
[10:01:11] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[10:01:11] [Client thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[10:01:11] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[10:01:11] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[10:01:12] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[10:01:12] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[10:01:12] [Client thread/INFO] [FML]: Applying holder lookups
[10:01:12] [Client thread/INFO] [FML]: Holder lookups applied
[10:01:12] [Client thread/INFO] [FML]: Applying holder lookups
[10:01:12] [Client thread/INFO] [FML]: Holder lookups applied
[10:01:12] [Client thread/INFO] [FML]: Applying holder lookups
[10:01:12] [Client thread/INFO] [FML]: Holder lookups applied
[10:01:12] [Client thread/INFO] [FML]: Applying holder lookups
[10:01:12] [Client thread/INFO] [FML]: Holder lookups applied
[10:01:12] [Client thread/INFO] [FML]: Injecting itemstacks
[10:01:12] [Client thread/INFO] [FML]: Itemstack injection complete
[10:01:14] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[10:01:14] [Thread-7/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[10:01:14] [Thread-7/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:01:14] [Thread-7/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[10:01:15] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[10:01:21] [Client thread/INFO] [FML]: Max texture size: 16384
[10:01:24] [Client thread/INFO] [net.minecraft.client.renderer.texture.TextureMap]: Created: 2048x2048 textures-atlas
[10:01:27] [Client thread/INFO] [FML]: Applying holder lookups
[10:01:27] [Client thread/INFO] [FML]: Holder lookups applied
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.moandjiezana.toml.Toml.getDouble(Toml.java:209)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at cope.cosmos.client.manager.managers.PresetManager.loadModules(PresetManager.java:141)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at cope.cosmos.client.manager.managers.PresetManager.load(PresetManager.java:60)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at cope.cosmos.client.manager.managers.PresetManager.<init>(PresetManager.java:38)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at cope.cosmos.client.Cosmos.init(Cosmos.java:92)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:01:27] [Client thread/INFO] [STDERR]: [cope.cosmos.client.manager.managers.PresetManager:loadModules:165]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:01:27] [Client thread/INFO] [FML]: Injecting itemstacks
[10:01:27] [Client thread/INFO] [FML]: Itemstack injection complete
[10:01:28] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[10:01:28] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[10:01:28] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[10:02:03] [Netty Client IO #1/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:03] [Netty Client IO #3/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:03] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:03] [Netty Client IO #2/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:03] [Netty Client IO #3/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:03] [Netty Client IO #1/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:04] [Netty Client IO #6/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:04] [Netty Client IO #5/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:04] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:04] [Netty Client IO #2/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER
[10:02:05] [Client thread/INFO] [net.minecraft.client.multiplayer.GuiConnecting]: Connecting to us.crystalpvp.cc, 25565
[10:02:07] [Netty Client IO #1/INFO] [FML]: Aborting client handshake "VANILLA"
[10:02:07] [Netty Client IO #1/INFO] [FML]: [Netty Client IO #1] Client side vanilla connection established
[10:02:07] [Netty Client IO #1/INFO] [FML]: Server protocol version 2
[10:02:08] [Client thread/INFO] [FML]: Applying holder lookups
[10:02:08] [Client thread/INFO] [FML]: Holder lookups applied
[10:02:08] [Netty Client IO #1/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, cosmos] at SERVER

**Comment by linustouchtips** [comment]
no i need the last 100 lines, not the first 100

**Comment by master7720** [comment]
java.lang.NullPointerException: Rendering screen
	at cope.cosmos.client.clickgui.util.BlurUtil.configureShader(BlurUtil.java:35)
	at cope.cosmos.client.clickgui.util.BlurUtil.blurRect(BlurUtil.java:70)
	at cope.cosmos.client.clickgui.windowed.window.Window.drawWindow(Window.java:67)
	at cope.cosmos.client.clickgui.windowed.window.ScrollableWindow.drawWindow(ScrollableWindow.java:35)
	at cope.cosmos.client.clickgui.windowed.window.TabbedWindow.drawWindow(TabbedWindow.java:34)
	at cope.cosmos.client.clickgui.windowed.window.windows.ConfigurationWindow.drawWindow(ConfigurationWindow.java:72)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.lambda$drawScreen$0(WindowGUI.java:36)
	at cope.cosmos.client.clickgui.windowed.WindowGUI$$Lambda$258/1688871501.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.func_73863_a(WindowGUI.java:35)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cope.cosmos.client.clickgui.util.BlurUtil.configureShader(BlurUtil.java:35)
	at cope.cosmos.client.clickgui.util.BlurUtil.blurRect(BlurUtil.java:70)
	at cope.cosmos.client.clickgui.windowed.window.Window.drawWindow(Window.java:67)
	at cope.cosmos.client.clickgui.windowed.window.ScrollableWindow.drawWindow(ScrollableWindow.java:35)
	at cope.cosmos.client.clickgui.windowed.window.TabbedWindow.drawWindow(TabbedWindow.java:34)
	at cope.cosmos.client.clickgui.windowed.window.windows.ConfigurationWindow.drawWindow(ConfigurationWindow.java:72)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.lambda$drawScreen$0(WindowGUI.java:36)
	at cope.cosmos.client.clickgui.windowed.WindowGUI$$Lambda$258/1688871501.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at cope.cosmos.client.clickgui.windowed.WindowGUI.func_73863_a(WindowGUI.java:35)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: cope.cosmos.client.clickgui.windowed.WindowGUI
	Mouse location: Scaled: (480, 254). Absolute: (960, 508)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 11 total; [EntityPlayerSP['PreparedSystem32'/565345, l='MpServer', x=4.75, y=121.00, z=-15.54], EntityOtherPlayerMP['Sceptt'/557339, l='MpServer', x=4.70, y=1.00, z=17.30], EntityOtherPlayerMP['NathanOwO'/562538, l='MpServer', x=4.30, y=1.00, z=17.33], EntityOtherPlayerMP['Redd'/548495, l='MpServer', x=-3.70, y=1.00, z=6.45], EntityOtherPlayerMP['PollosxD'/547994, l='MpServer', x=1.30, y=3.00, z=6.70], EntityOtherPlayerMP['PuggersKEK'/560077, l='MpServer', x=3.30, y=1.00, z=15.30], EntityOtherPlayerMP['blank_dvth'/538318, l='MpServer', x=5.52, y=2.00, z=5.54], EntityOtherPlayerMP['zNeuX1'/542951, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['paowe30'/548094, l='MpServer', x=5.30, y=2.00, z=6.04], EntityOtherPlayerMP['W0M3N'/559715, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['0x0x0x0x0x0'/561464, l='MpServer', x=0.10, y=122.00, z=5.36]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,122,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 135848 game time, 14500 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 36 total; [EntityPlayerSP['PreparedSystem32'/565345, l='MpServer', x=4.75, y=121.00, z=-15.54], EntityExpBottle['entity.ThrownExpBottle.name'/566088, l='MpServer', x=-2.48, y=2.64, z=5.77], EntityOtherPlayerMP['Sceptt'/557339, l='MpServer', x=4.70, y=1.00, z=17.30], EntityExpBottle['entity.ThrownExpBottle.name'/566089, l='MpServer', x=1.94, y=4.41, z=6.42], EntityOtherPlayerMP['NathanOwO'/562538, l='MpServer', x=4.30, y=1.00, z=17.33], EntityOtherPlayerMP['W0M3N'/559715, l='MpServer', x=0.00, y=122.00, z=0.00], EntityXPOrb['Experience Orb'/566090, l='MpServer', x=-3.18, y=2.76, z=6.20], EntityOtherPlayerMP['Redd'/548495, l='MpServer', x=-3.70, y=1.00, z=6.45], EntityXPOrb['Experience Orb'/566091, l='MpServer', x=-3.13, y=2.83, z=6.13], EntityOtherPlayerMP['PollosxD'/547994, l='MpServer', x=1.30, y=3.00, z=6.70], EntityXPOrb['Experience Orb'/566092, l='MpServer', x=-3.17, y=2.72, z=6.13], EntityOtherPlayerMP['PuggersKEK'/560077, l='MpServer', x=3.30, y=1.00, z=15.30], EntityOtherPlayerMP['PuggersKEK'/560077, l='MpServer', x=3.30, y=1.00, z=15.30], EntityXPOrb['Experience Orb'/566093, l='MpServer', x=-3.15, y=2.72, z=6.17], EntityOtherPlayerMP['blank_dvth'/538318, l='MpServer', x=5.52, y=2.00, z=5.54], EntityOtherPlayerMP['blank_dvth'/538318, l='MpServer', x=5.52, y=2.00, z=5.54], EntityOtherPlayerMP['Redd'/548495, l='MpServer', x=-3.70, y=1.00, z=6.45], EntityOtherPlayerMP['zNeuX1'/542951, l='MpServer', x=0.00, y=122.00, z=0.00], EntityExpBottle['entity.ThrownExpBottle.name'/566095, l='MpServer', x=-3.10, y=2.61, z=6.11], EntityExpBottle['entity.ThrownExpBottle.name'/566080, l='MpServer', x=2.57, y=4.11, z=6.17], EntityXPOrb['Experience Orb'/566086, l='MpServer', x=1.50, y=4.42, z=6.49], EntityExpBottle['entity.ThrownExpBottle.name'/566087, l='MpServer', x=-2.44, y=2.63, z=5.81], EntityOtherPlayerMP['PollosxD'/547994, l='MpServer', x=1.30, y=3.00, z=6.70], EntityOtherPlayerMP['Sceptt'/557339, l='MpServer', x=4.70, y=1.00, z=17.30], EntityExpBottle['entity.ThrownExpBottle.name'/566096, l='MpServer', x=-3.10, y=2.58, z=6.09], EntityOtherPlayerMP['NathanOwO'/562538, l='MpServer', x=4.30, y=1.00, z=17.33], EntityOtherPlayerMP['W0M3N'/559715, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['zNeuX1'/542951, l='MpServer', x=0.00, y=122.00, z=0.00], EntityOtherPlayerMP['paowe30'/548094, l='MpServer', x=5.30, y=2.00, z=6.04], EntityOtherPlayerMP['0x0x0x0x0x0'/561464, l='MpServer', x=15.37, y=2.00, z=13.51], EntityOtherPlayerMP['paowe30'/548094, l='MpServer', x=5.30, y=2.00, z=6.04], EntityExpBottle['entity.ThrownExpBottle.name'/566078, l='MpServer', x=-1.85, y=2.62, z=5.54], EntityExpBottle['entity.ThrownExpBottle.name'/566079, l='MpServer', x=-1.89, y=2.58, z=5.51], EntityOtherPlayerMP['0x0x0x0x0x0'/561464, l='MpServer', x=0.10, y=122.00, z=5.36], EntityArmorStand['§fType §b§l/kitcreator §fto §f§lget items'/825, l='MpServer', x=-8.50, y=124.00, z=8.52], EntityArmorStand['§fType §b§l/kitcreator §fto §f§lget items'/827, l='MpServer', x=8.51, y=124.00, z=-8.51]]
	Retry entities: 0 total; []
	Server brand: Crystal (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by linustouchtips** [comment]
Build from new source, I might have already fixed that

**Comment by linustouchtips** [comment]
Build from new source, I might have already fixed that

**Comment by master7720** [comment]
ok ok

**Comment by master7720** [comment]
thanks dis helped i can now own cc with cosmos!
