### ISSUE TITLE
[BUG] Crashes when disables crystal aura

### ISSUE THREAD

**Issue by Fiyxz** [momentumdevelopment/cosmos#149]
Issue:
* What is the bug that you would like addressed?
* crystal aura crashes. after the 2 times of being disabled 

Context:
* When does this bug happen? Does it persist after restart/toggle? yeah I have deleted the folder 2 times and restarted 

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated? I run Kami blue dev, spidersence, and COSMOS(superior client ofc)  The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: 255 That is the error I got 

Config:
* Attach any relevant parts of your config here. umm idk what to put here I guess my crystal aura that is the only thing I use this client for and strafe 
Enabled = false
Drawn = false
Bind = 44
Explode = true
Explode-Range = 6.0
Explode-WallRange = 3.5
Explode-Delay = 60.0
Explode-RandomDelay = 0.0
Explode-SwitchDelay = 0.0
Explode-TicksExisted = 0.0
Explode-Damage = 2.0
Explode-LocalDamage = 5.0
Explode-Limit = 10.0
Explode-Packet = true
Explode-Inhibit = false
Explode-Hand = "SYNC"
Explode-Weakness = "NONE"
Place = true
Place-Range = 6.0
Place-WallRange = 3.5
Place-Delay = 0.0
Place-Damage = 2.0
Place-LocalDamage = 5.0
Place-Packet = true
Place-Interact = "NORMAL"
Place-Raytrace = "DOUBLE"
Place-Hand = "MAINHAND"
Place-Switch = "NONE"
Pause = true
Pause-Health = 9.0
Pause-Safety = true
Pause-Eating = false
Pause-Mining = false
Pause-Mending = false
Override = false
Override-Health = 10.0
Override-Threshold = 0.0
Override-Armor = 86.0
Rotation = "NONE"
Rotation-Limit = "NONE"
Rotation-When = "BOTH"
Rotation-Random = 0.0
Calculations = true
Calculations-Timing = "LINEAR"
Calculations-Placements = "NATIVE"
Calculations-Logic = "DAMAGE"
Calculations-Sync = "SOUND"
Calculations-Prediction = false
Calculations-IgnoreTerrain = false
Target = "LOWESTHEALTH"
Target-Range = 10.0
Target-Players = true
Target-Passives = false
Target-Neutrals = false
Target-Hostiles = false
Render = true
Render-Mode = "BOTH"
Render-Text = "NONE"
Render-Width = 1.5

**Comment by linustouchtips** [comment]
could you send your latest.log file

**Comment by Fiyxz** [comment]
ok let me do that

**Comment by Fiyxz** [comment]
Where do I find that?

**Comment by Fiyxz** [comment]
I got to my logs

**Comment by Fiyxz** [comment]
here it is 
[14:00:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/*************/Library/Application Support/minecraft/crash-reports/crash-2021-12-23_14.00.06-client.txt

**Comment by linustouchtips** [comment]
its in your minecraft folder, in a folder called logs, you're looking for a file that says latest.log (i need the whole file btw)

**Comment by Fiyxz** [comment]
Oh, 
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1173054336 bytes (1118 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                            | Signature                                |
	|:------ |:----------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                     | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                     | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cosmos      | 1.2.0        | cosmos-1.2.0.jar                  | None                                     |
	| LCHIJA | spidersense | v2.3.9       | spidersense-v2.3.9.jar            | None                                     |
	| LCHIJA | kamiblue    | 2.02.xx-dev  | client-2.02.xx-dev-ht-v09.8.5.jar | None                                     |

	Loaded coremods (and transformers): 
SpiderSense (spidersense-v2.3.9.jar)
  
KAMIBlueMixinLoader (client-2.02.xx-dev-ht-v09.8.5.jar)
  
MixinLoader (cosmos-1.2.0.jar)
  
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.2
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-16.5.2, Intel Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: waopackhat
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-16.5.2
	OpenGlRenderer: Intel Iris Pro OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 8
[14:00:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/**********/Library/Application Support/minecraft/crash-reports/crash-2021-12-23_14.00.06-client.txt

**Comment by Fiyxz** [comment]
Is that what you need?

**Comment by Fiyxz** [comment]
Or this it says crash report on it, 
WARNING: coremods are present:
  SpiderSense (spidersense-v2.3.9.jar)
  KAMIBlueMixinLoader (client-2.02.xx-dev-ht-v09.8.5.jar)
  MixinLoader (cosmos-1.2.0.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/23/21 1:45 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.enchantment.EnchantmentProtection.func_77318_a(SourceFile:73)
	at net.minecraft.enchantment.EnchantmentHelper$ModifierDamage.func_77493_a(EnchantmentHelper.java:485)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:124)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
	at net.minecraft.enchantment.EnchantmentHelper.func_77508_a(EnchantmentHelper.java:142)
	at com.gamesense.api.util.world.combat.ac.PlayerInfo.<init>(PlayerInfo.java:51)
	at com.gamesense.client.module.modules.combat.AutoCrystal.lambda$new$1(AutoCrystal.java:138)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:89)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.alpine.EventManager.post(EventManager.java:89)
	at com.gamesense.client.manager.managers.ClientEventManager.onTick(ClientEventManager.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_87_ClientEventManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.enchantment.EnchantmentProtection.func_77318_a(SourceFile:73)
	at net.minecraft.enchantment.EnchantmentHelper$ModifierDamage.func_77493_a(EnchantmentHelper.java:485)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:124)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
	at net.minecraft.enchantment.EnchantmentHelper.func_77508_a(EnchantmentHelper.java:142)
	at com.gamesense.api.util.world.combat.ac.PlayerInfo.<init>(PlayerInfo.java:51)
	at com.gamesense.client.module.modules.combat.AutoCrystal.lambda$new$1(AutoCrystal.java:138)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:89)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.zero.alpine.EventManager.post(EventManager.java:89)
	at com.gamesense.client.manager.managers.ClientEventManager.onTick(ClientEventManager.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_87_ClientEventManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['Fiyxz'/421192, l='MpServer', x=-53.70, y=3.00, z=226.67], EntityOtherPlayerMP['AmogusDrink'/415907, l='MpServer', x=-56.70, y=126.00, z=222.78], EntityOtherPlayerMP['Fiyxz'/384689171, l='MpServer', x=-53.50, y=3.00, z=226.50]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,75,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 166382 game time, 868399408 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 9 total; [EntityPlayerSP['Fiyxz'/421192, l='MpServer', x=-53.70, y=3.00, z=226.67], EntityEnderCrystal['entity.EnderCrystal.name'/245939, l='MpServer', x=-69.50, y=5.00, z=222.50], EntityEnderCrystal['entity.EnderCrystal.name'/432550, l='MpServer', x=-52.50, y=4.00, z=226.50], EntityOtherPlayerMP['Joker_god_'/380732, l='MpServer', x=-100.90, y=4.57, z=255.11], EntityOtherPlayerMP['AmogusDrink'/415907, l='MpServer', x=-56.70, y=126.00, z=222.78], EntityOtherPlayerMP['AmogusDrink'/415907, l='MpServer', x=-56.70, y=126.00, z=222.78], EntityOtherPlayerMP['ltau'/425817, l='MpServer', x=-105.94, y=248.73, z=210.04], EntityOtherPlayerMP['Fiyxz'/384689171, l='MpServer', x=-53.50, y=3.00, z=226.50], EntityOtherPlayerMP['Fiyxz'/384689171, l='MpServer', x=-53.50, y=3.00, z=226.50]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- Papaya
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 910148496 bytes (867 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                            | Signature                                |
	|:------ |:----------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                     | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                     | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cosmos      | 1.2.0        | cosmos-1.2.0.jar                  | None                                     |
	| LCHIJA | spidersense | v2.3.9       | spidersense-v2.3.9.jar            | None                                     |
	| LCHIJA | kamiblue    | 2.02.xx-dev  | client-2.02.xx-dev-ht-v09.8.5.jar | None                                     |

	Loaded coremods (and transformers): 
SpiderSense (spidersense-v2.3.9.jar)
  
KAMIBlueMixinLoader (client-2.02.xx-dev-ht-v09.8.5.jar)
  
MixinLoader (cosmos-1.2.0.jar)
  
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.2
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-16.5.2, Intel Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: waopackhat
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-16.5.2
	OpenGlRenderer: Intel Iris Pro OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 8
[13:45:26] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/***********/Library/Application Support/minecraft/crash-reports/crash-2021-12-23_13.45.25-client.txt

**Comment by linustouchtips** [comment]
do you have to autocrystals on?

**Comment by Fiyxz** [comment]
No I dont think let me check

**Comment by Fiyxz** [comment]
It was im so fucking sorry for wasting your time while I got you sorta another bug/suggestion when you enable surround/on the packet option it doesn't fully work when i try to eat it places a block idk if you can fix that but thanks

**Comment by linustouchtips** [comment]
you're fine, and sure

**Comment by Fiyxz** [comment]
thx
