### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#185]
---- Minecraft Crash Report ----
// My bad.

Time: 2/4/22 8:16 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at cope.cosmos.client.features.modules.movement.ElytraFlight.onTravel(ElytraFlight.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_ElytraFlight_onTravel_TravelEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.entity.player.EntityPlayer.handler$travel$zzg000(EntityPlayer.java:2772)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cope.cosmos.client.features.modules.movement.ElytraFlight.onTravel(ElytraFlight.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_ElytraFlight_onTravel_TravelEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.entity.player.EntityPlayer.handler$travel$zzg000(EntityPlayer.java:2772)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 217
	Entity Name: PreparedSystem32
	Entity's Exact location: 12552678.47, 92.00, 12552737.99
	Entity's Block location: World: (12552678,92,12552737), Chunk: (at 6,5,1 in 784542,784546; contains blocks 12552672,0,12552736 to 12552687,255,12552751), Region: (24516,24517; contains chunks 784512,784544 to 784543,784575, blocks 12552192,0,12552704 to 12552703,255,12553215)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@624e02da
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by master7720** [comment]
@Sxmurai you still ratting ppl lol

**Comment by Sxmurai** [comment]
@master7720 you still only making pull requests for mcmod.info and throw Alfie under the bus because you didn't want to loose access to gerald(hack)?

**Comment by Sxmurai** [comment]
lol gerald has all the screenshots dunno why ur tryna deny it, me and the other dude both sent screenshots 💀 now keep this out of cosmos issues and take it to my discord dms

**Comment by Wolfsurge** [comment]
Fixed in #201
