### ISSUE TITLE
[BUG] Crash on PacketStrict criticals

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#205]
Issue:
big erro

```
23:44:03.547
game
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) ~[log4j-core-2.15.0.jar:2.15.0]
23:44:03.547
game
at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[log4j-core-2.15.0.jar:2.15.0]
23:44:03.547
game
at org.apache.logging.log4j.core.Logger.log(Logger.java:161) ~[log4j-core-2.15.0.jar:2.15.0]
23:44:03.547
game
at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205) ~[log4j-api-2.15.0.jar:2.15.0]
23:44:03.547
game
at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159) ~[log4j-api-2.15.0.jar:2.15.0]
23:44:03.548
game
at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[log4j-api-2.15.0.jar:2.15.0]
23:44:03.548
game
at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2040) ~[log4j-api-2.15.0.jar:2.15.0]
23:44:03.548
game
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1907) ~[log4j-api-2.15.0.jar:2.15.0]
23:44:03.548
game
at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:871) ~[log4j-api-2.15.0.jar:2.15.0]
23:44:03.548
game
at net.minecraftforge.fml.common.eventhandler.EventBus.handleException(EventBus.java:203) ~[EventBus.class:?]
23:44:03.548
game
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) ~[EventBus.class:?]
23:44:03.548
game
at net.minecraft.network.NetworkManager.handler$onPacketSend$zzj000(NetworkManager.java:542) ~[gw.class:?]
23:44:03.548
game
at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java) ~[gw.class:?]
23:44:03.548
game
at cope.cosmos.client.features.modules.combat.CriticalsModule.onPacketSend(CriticalsModule.java:167) ~[CriticalsModule.class:?]
23:44:03.548
game
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_CriticalsModule_onPacketSend_PacketSendEvent.invoke(.dynamic) ~[?:?]
23:44:03.548
game
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
23:44:03.548
game
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
23:44:03.548
game
at net.minecraft.network.NetworkManager.handler$onPacketSend$zzj000(NetworkManager.java:542) ~[gw.class:?]
23:44:03.548
game
at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java) ~[gw.class:?]
```

Context:
criticals go on on with packetstrict and you attack entity and rip game

Environment: 
2b2t.dev

Config:
* Attach any relevant parts of your config here.

**Comment by master7720** [comment]
> Issue: big erro
> 
> ```
> 23:44:03.547
> game
> at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) ~[log4j-core-2.15.0.jar:2.15.0]
> 23:44:03.547
> game
> at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[log4j-core-2.15.0.jar:2.15.0]
> 23:44:03.547
> game
> at org.apache.logging.log4j.core.Logger.log(Logger.java:161) ~[log4j-core-2.15.0.jar:2.15.0]
> 23:44:03.547
> game
> at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205) ~[log4j-api-2.15.0.jar:2.15.0]
> 23:44:03.547
> game
> at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159) ~[log4j-api-2.15.0.jar:2.15.0]
> 23:44:03.548
> game
> at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[log4j-api-2.15.0.jar:2.15.0]
> 23:44:03.548
> game
> at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2040) ~[log4j-api-2.15.0.jar:2.15.0]
> 23:44:03.548
> game
> at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1907) ~[log4j-api-2.15.0.jar:2.15.0]
> 23:44:03.548
> game
> at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:871) ~[log4j-api-2.15.0.jar:2.15.0]
> 23:44:03.548
> game
> at net.minecraftforge.fml.common.eventhandler.EventBus.handleException(EventBus.java:203) ~[EventBus.class:?]
> 23:44:03.548
> game
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) ~[EventBus.class:?]
> 23:44:03.548
> game
> at net.minecraft.network.NetworkManager.handler$onPacketSend$zzj000(NetworkManager.java:542) ~[gw.class:?]
> 23:44:03.548
> game
> at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java) ~[gw.class:?]
> 23:44:03.548
> game
> at cope.cosmos.client.features.modules.combat.CriticalsModule.onPacketSend(CriticalsModule.java:167) ~[CriticalsModule.class:?]
> 23:44:03.548
> game
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_CriticalsModule_onPacketSend_PacketSendEvent.invoke(.dynamic) ~[?:?]
> 23:44:03.548
> game
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 23:44:03.548
> game
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
> 23:44:03.548
> game
> at net.minecraft.network.NetworkManager.handler$onPacketSend$zzj000(NetworkManager.java:542) ~[gw.class:?]
> 23:44:03.548
> game
> at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java) ~[gw.class:?]
> ```
> 
> Context: criticals go on on with packetstrict and you attack entity and rip game
> 
> Environment: 2b2t.dev
> 
> Config:
> 
>     * Attach any relevant parts of your config here.

```
at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) ~[log4j-core-2.15.0.jar:2.15.0]``` OMG LOG4J!!!!
