### ISSUE TITLE
[BUG] Threadmanager issues for holefill

### ISSUE THREAD

**Issue by CynicalMuffin** [momentumdevelopment/cosmos#78]
So the issue here is holefill's threadmanager is causing lag spikes because the rendering threads are not synced with the client's(at least thats what linus told me) and these lag spikes are really bad causing about 3 seconds of spikes every 10 seconds.

im not sure this happens on better pcs but i have tried it and the error logs still come but the spikes are not very noticeable it just causes a slight frame drop

Error logs:

[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: java.lang.IllegalArgumentException: Comparison method violates its general contract!
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.mergeHi(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.mergeAt(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.mergeForceCollapse(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.sort(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.Arrays.sort(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.ArrayList.sort(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.Sink$ChainedReference.end(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.util.world.BlockUtil.getSurroundingBlocks(BlockUtil.java:79)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.HoleManager.searchHoles(HoleManager.java:40)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.HoleManager.onThread(HoleManager.java:33)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.ThreadManager$ClientService.lambda$run$1(ThreadManager.java:58)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.ArrayList.forEach(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.ThreadManager$ClientService.run(ThreadManager.java:49)

And another one:

[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.mergeAt(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.mergeForceCollapse(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.TimSort.sort(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.Arrays.sort(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.ArrayList.sort(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.Sink$ChainedReference.end(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.util.world.BlockUtil.getSurroundingBlocks(BlockUtil.java:79)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.HoleManager.searchHoles(HoleManager.java:40)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.HoleManager.onThread(HoleManager.java:33)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.ThreadManager$ClientService.lambda$run$1(ThreadManager.java:58)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at java.util.ArrayList.forEach(Unknown Source)
[07:35:38] [Thread-10/INFO] [STDERR]: [cope.cosmos.client.manager.managers.ThreadManager$ClientService:lambda$run$1:60]: 	at cope.cosmos.client.manager.managers.ThreadManager$ClientService.run(ThreadManager.java:49)

the java.util.timsort.mergeforcecollapse/mergehi/mergeat are different variations of the logs that begin for the errors

if you need the full client logs from start i can share them too

**Comment by CynicalMuffin** [comment]
@linustouchtips  both are fixed the speedmine and holefill?
